### ISSUE TITLE
Make compatible with php7

### ISSUE THREAD

**Issue by addshore** [sandrokeil/HtmlElement#9]
It would be great to be able to install this with php7!
Currently composer requires ~5.3 :(

**Comment by sandrokeil** [comment]
That's right. I'm busy at the moment. Do want to bring a PR please?

**Comment by sandrokeil** [comment]
I've started working on it in [branch php7](https://github.com/sandrokeil/HtmlElement/tree/php7).

**Comment by sandrokeil** [comment]
@addshore It's [done](https://github.com/sandrokeil/HtmlElement/releases/tag/2.0.0) :tada:
